### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by dexter845** [JasinYip/ladder-custom-rules#1]
Hi JasinYip,

I would like to know about Clive Young (the founder of hentai.js).  He initialized the repository for the promising mvvm framework 8 years back. the repository has not been updated since then. Looks like he is also inactive on github from 2020.

Thank you.

**Comment by JasinYip** [comment]
@dexter845 Sorry, I don't know him either

**Comment by jalixdesign** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
buttonwild, @tsingzdev, @zhaohaoren, @akimisen, @fichtl, @thienduynguyen, @Yubaba0315, @guopi, @Klauxs, @janeping, @ecsfu, @johnnyleeRH, @nanfangyinan1, @kagayakidan, @UndefinedVoidNull, @riverzzj, @o-XuX-o, @remember-5, @FlyWay-one, @carycoti, @litengxu, @Louisjzhao, @ruii166, @hhxx2015, @hushuozhi, @zdz72113, @conan71, @overXsky, @guobailin, @RainWithDrop, @fengsenlin5293, @mcmdhr, @nishiting, @1162303953, @ruishuQU, @hairhan-tod, @XRFXRF, @souxun2015, @tcandzq, @ian-xu, @xrff, @l7i, @sxhysj, @ForAxel, @lucky2046, @ashwin-patil, @Payuing, @DragonV96, @xinbingliang, @wegamekinglc
